### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by bitkarrot** [invincible-privacy/donate#1]
Thanks for starting this. do you also allow nostr projects that use lightning? (self custodial)

@1440000bytes

**Comment by 1440000bytes** [comment]
Yes. If it's related to privacy.

**Comment by bitkarrot** [comment]
I want to add hivetalk to this if possible. its a privacy focused webrtc server with lightning and nostr enhancements and a goal of protecting free speech. any feedback is welcome. How can i help you get this invincible-privacy initiative off the ground? 

https://github.com/HiveTalk/hivetalksfu

**Comment by 1440000bytes** [comment]
Looks good. I think it can be added as its better in terms of privacy compared to other tools used by people for video calls. However, I will have to review code and test it for any detailed feedback.

> How can i help you get this invincible-privacy initiative off the ground?

- I need some help to improve the website and complete it. Hopefully I will do it today.
- Share about it on twitter, nostr etc.
- Contact different people, organizations to support the projects and initiative in next few days.

**Comment by bitkarrot** [comment]
> Looks good. I think it can be added as its better in terms of privacy compared to other tools used by people for video calls. However, I will have to review code and test it for any detailed feedback.
> 
 Would love to have a review, that would be most helpful. 

- Can definitely share on twitter/nostr

**Comment by 1440000bytes** [comment]
![image](https://github.com/invincible-privacy/donate/assets/147166694/01270610-8aa1-4537-8062-700de8d39dc3)

I have added hivetalk
